name: Teste Básico
on:
  workflow_dispatch:  # Permite execução manual
  schedule:
    - cron: '*/5 * * * *'  # A cada 5 minutos

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
    - name: Passo 1
      run: echo "✅ Funcionou em $(date)"