name: Conditional Commit

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main 

    - name: Get current hour and generate random number
      run: |
        CURRENT_HOUR=$(date -u +%H)
        RANDOM_NUMBER=$(( $RANDOM % 10 + 1 ))
        echo "CURRENT_HOUR=$CURRENT_HOUR" >> $GITHUB_ENV
        echo "RANDOM_NUMBER=$RANDOM_NUMBER" >> $GITHUB_ENV
        
    - name: Create file and commit (only if conditions are met)
      if: env.CURRENT_HOUR >= 7 && env.RANDOM_NUMBER > 6
      run: |
        FILE="commit_number.md"
        if [ ! -f "$FILE" ]; then
          echo "Hello!" > "$FILE"
          echo "commit number: 1" >> "$FILE"
        else
          CURRENT_COUNT=$(grep -oP 'commit number: \K\d+' "$FILE")
          if [ -z "$CURRENT_COUNT" ]; then
            CURRENT_COUNT=0
          fi
          NEXT_COUNT=$((CURRENT_COUNT + 1))
          sed -i "/commit number: /c\commit number: $NEXT_COUNT" "$FILE"
        fi
        git config --global user.name "DeborAguiar"
        git config --global user.email "debora.aguiar.boni@gmail.com"
        git add "$FILE"
        git commit -m "Hello! nice to meet you"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/DeborAguiar/test.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}