name: Print FOI

on:
  schedule:
    - cron: '*/1 * * * *'  # Executa a cada minuto

jobs:
  print-foi:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print FOI
      run: echo "FOI"