name: Auto Commit

on:
  schedule:
    - cron: '*/5 * * * *'  # Reduzi para 5 minutos para testes
  workflow_dispatch:  # Permite execução manual

permissions:
  contents: write  # Permissão explícita para push

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0  # Garante o histórico completo

    - name: Update file
      run: |
        FILE="commit_number.md"
        # Cria ou atualiza o arquivo
        if [ ! -f "$FILE" ]; then
          echo "Initial commit" > "$FILE"
          echo "count: 1" >> "$FILE"
        else
          COUNT=$(grep -oP 'count: \K\d+' "$FILE" || echo "0")
          NEW_COUNT=$((COUNT + 1))
          sed -i "s/count: .*/count: $NEW_COUNT/" "$FILE"
        fi

        # Configura git
        git config --global user.name "DeborAguiar"
        git config --global user.email "debora.aguiar.boni@gmail.com"
        
        # Commit e push (com tratamento de erros)
        git add "$FILE"
        git diff-index --quiet HEAD || git commit -m "Update count to $NEW_COUNT"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}