name: Teste Básico
on:
  workflow_dispatch:  # Permite execução manual
  schedule:
    - cron: '*/30 * * * *'  # Minimo de 15 minutos
  push:
    branches: [ main ]     # Dispara no push

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main 

    - name: Get current time and random number
      id: set_conditions
      run: |
        CURRENT_HOUR=$(TZ='America/Sao_Paulo' date +%H)
        CURRENT_MINUTE=$(TZ='America/Sao_Paulo' date +%M)
        RANDOM_NUMBER=$(( $RANDOM % 10 + 1 ))

        echo "🕒 Horário de Brasília: $CURRENT_HOUR:$CURRENT_MINUTE"
        echo "🎲 Número Aleatório: $RANDOM_NUMBER"
        echo "🔍 Depois das 19h? $([ 10#$CURRENT_HOUR -ge 19 ] && echo "SIM" || echo "NÃO")"
        echo "🔍 Número > 6? $([ 10#$RANDOM_NUMBER -gt 6 ] && echo "SIM" || echo "NÃO")"

        echo "CURRENT_HOUR=$CURRENT_HOUR" >> $GITHUB_ENV
        echo "RANDOM_NUMBER=$RANDOM_NUMBER" >> $GITHUB_ENV
        echo "should_run=$(( 10#$CURRENT_HOUR >= 19 && 10#$RANDOM_NUMBER > 6 ))" >> $GITHUB_OUTPUT

    - name: Decision Log
      run: |
        echo "### DECISÃO ###"
        echo "Deve executar? $([ ${{ steps.set_conditions.outputs.should_run }} == '1' ] && echo "✅ SIM" || echo "❌ NÃO")"
        echo "- Hora (BR): ${{ env.CURRENT_HOUR }}"
        echo "- Aleatório: ${{ env.RANDOM_NUMBER }}"

    - name: Create file and commit
      if: steps.set_conditions.outputs.should_run == '1'
      run: |
        FILE="commit_number.md"
        if [ ! -f "$FILE" ]; then
          echo "Hello!" > "$FILE"
          echo "commit number: 1" >> "$FILE"
        else
          CURRENT_COUNT=$(grep -oP 'commit number: \K\d+' "$FILE" || echo "0")
          NEXT_COUNT=$((CURRENT_COUNT + 1))
          sed -i "s/commit number: .*/commit number: $NEXT_COUNT/" "$FILE"
        fi

        git config --global user.name "DeborAguiar"
        git config --global user.email "debora.aguiar.boni@gmail.com"
        git add "$FILE"
        git commit -m "Update commit number: $NEXT_COUNT" || echo "⚠️ Sem alterações"
        git push || echo "⚠️ Falha no push"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}