name: Teste Básico
on:
  workflow_dispatch:  # Permite execução manual
  schedule:
    - cron: '*/5 * * * *'  # 5 minutos
  push:
    branches: [ main ]     # Dispara no push

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
    - name: Passo 1
      run: echo "✅ Funcionou em $(date)"